export const FAMILY_SCHOOL_COMMUNICATION_SERVICE = {
  slug: "family-school-communication",
  name: "التواصل بين الأسرة والمدرسة",
  description:
    "توثيق التواصل مع الأسرة وولي الأمر ونتائج التواصل ضمن سجلات الخدمة.",
};

export const GUARDIAN_SUMMONS_WORKFLOW = {
  workflowType: "guardian-summons",
  name: "استدعاء ولي أمر",
  version: 1,
  steps: [
    {
      title: "اختيار الطالب/الطالبة",
      description:
        "اختر الطالب/الطالبة من بيانات الطلاب ليتم ربط الاستدعاء بسجل الطالب وولي الأمر.",
      order: 1,
      fields: [
        {
          key: "student_picker",
          label: "اختيار الطالب/الطالبة",
          type: "STUDENT_PICKER",
          isRequired: true,
          order: 1,
          helpText: "ابحث باسم الطالب/الطالبة أو رقم الهوية.",
          options: [],
        },
      ],
    },
    {
      title: "أسباب الاستدعاء",
      description: "يمكن اختيار أكثر من سبب للاستدعاء.",
      order: 2,
      fields: [
        {
          key: "summons_reasons",
          label: "أسباب استدعاء ولي الأمر",
          type: "MULTI_SELECT",
          isRequired: true,
          order: 1,
          allowOther: true,
          helpText:
            "اختر كل الأسباب المناسبة للحالة. ستظهر الأسباب المختارة في خطاب الاستدعاء.",
          options: [
            ["academic_weakness", "ضعف التحصيل الدراسي."],
            ["low_academic_performance", "تدني مستوى الأداء الأكاديمي."],
            ["academic_follow_up", "متابعة المستوى الدراسي للطالب."],
            ["frequent_absence", "كثرة الغياب."],
            ["morning_late", "التأخر الصباحي المتكرر."],
            ["irregular_attendance", "عدم الالتزام بالحضور المنتظم."],
            ["behavior_problem", "وجود مشكلة سلوكية."],
            ["repeated_behavior_violations", "تكرار المخالفات السلوكية."],
            ["school_rules", "عدم التقيد بأنظمة المدرسة وتعليماتها."],
            ["fight_or_abuse", "المشاجرات أو الاعتداء اللفظي/الجسدي."],
            ["low_motivation", "تدني الدافعية للتعلم."],
            ["homework_neglect", "إهمال الواجبات والمهام الدراسية."],
            ["low_test_scores", "انخفاض درجات الاختبارات."],
            ["academic_plan", "الحاجة إلى وضع خطة علاجية أكاديمية."],
            ["psych_social", "متابعة حالة الطالب النفسية أو الاجتماعية."],
            ["teacher_notes", "مناقشة ملاحظات المعلمين حول الطالب."],
            ["behavior_plan", "متابعة برنامج تعديل السلوك."],
            ["devices_violation", "التنبيه على مخالفات استخدام الأجهزة أو وسائل التقنية."],
            ["school_property", "المحافظة على الممتلكات المدرسية."],
            ["discipline_drop", "دراسة أسباب تدني الانضباط المدرسي."],
            ["family_cooperation", "تعزيز التعاون بين المدرسة والأسرة لمصلحة الطالب."],
            ["special_needs", "مناقشة احتياجات الطالب التعليمية أو التربوية الخاصة."],
            ["bullying", "متابعة حالات التنمر كممارس أو متضرر."],
            ["student_data_update", "استكمال أو تحديث بيانات الطالب."],
            ["leaving_during_day", "مناقشة تكرار الاستئذان أو الخروج أثناء اليوم الدراسي."],
          ],
        },
      ],
    },
    {
      title: "موعد وطريقة الاستدعاء",
      description: "حدد موعد حضور ولي الأمر وطريقة إشعاره.",
      order: 3,
      fields: [
        {
          key: "summons_day",
          label: "يوم الحضور",
          type: "TEXT",
          isRequired: true,
          order: 1,
          placeholder: "مثال: الأحد",
          options: [],
        },
        {
          key: "summons_date",
          label: "تاريخ الحضور",
          type: "DATE",
          isRequired: true,
          order: 2,
          options: [],
        },
        {
          key: "summons_time",
          label: "وقت الحضور",
          type: "TEXT",
          isRequired: true,
          order: 3,
          placeholder: "مثال: 09:00",
          options: [],
        },
        {
          key: "summons_period",
          label: "الفترة",
          type: "SELECT",
          isRequired: true,
          order: 4,
          options: [
            ["morning", "صباحًا"],
            ["evening", "مساءً"],
          ],
        },
        {
          key: "notification_method",
          label: "طريقة إشعار ولي الأمر",
          type: "SELECT",
          isRequired: true,
          order: 5,
          allowOther: true,
          options: [
            ["paper", "خطاب ورقي"],
            ["phone", "اتصال هاتفي"],
            ["sms", "رسالة نصية"],
            ["whatsapp", "واتساب"],
            ["school_platform", "منصة المدرسة"],
          ],
        },
        {
          key: "priority",
          label: "أولوية الاستدعاء",
          type: "SELECT",
          isRequired: true,
          order: 6,
          options: [
            ["normal", "عادي"],
            ["important", "مهم"],
            ["urgent", "عاجل"],
          ],
        },
      ],
    },
    {
      title: "ما بعد الاستدعاء",
      description:
        "توثق هذه البيانات داخل النظام ولا تظهر في خطاب الاستدعاء الرسمي المختصر.",
      order: 4,
      fields: [
        {
          key: "summons_result",
          label: "نتيجة الاستدعاء",
          type: "SELECT",
          isRequired: true,
          order: 1,
          options: [
            ["pending", "لم يتم بعد"],
            ["attended", "حضر ولي الأمر"],
            ["not_attended", "لم يحضر ولي الأمر"],
            ["phone_contact", "تم التواصل هاتفيًا بدل الحضور"],
            ["postponed", "تم تأجيل الموعد"],
            ["closed_without_attendance", "تم إغلاق الاستدعاء بدون حضور"],
          ],
        },
        {
          key: "discussion_summary",
          label: "ما تم مناقشته",
          type: "TEXTAREA",
          isRequired: false,
          order: 2,
          dependsOnFieldKey: "summons_result",
          linkedToValue: "attended",
          options: [],
        },
        {
          key: "agreed_actions",
          label: "الإجراءات المتفق عليها",
          type: "TEXTAREA",
          isRequired: false,
          order: 3,
          dependsOnFieldKey: "summons_result",
          linkedToValue: "attended",
          options: [],
        },
        {
          key: "not_attended_next_action",
          label: "الإجراء التالي عند عدم الحضور",
          type: "SELECT",
          isRequired: false,
          order: 4,
          dependsOnFieldKey: "summons_result",
          linkedToValue: "not_attended",
          allowOther: true,
          options: [
            ["resummon", "إعادة الاستدعاء"],
            ["phone_contact", "التواصل الهاتفي"],
            ["escalate_admin", "تصعيد للإدارة"],
            ["document_only", "الاكتفاء بالتوثيق"],
          ],
        },
        {
          key: "follow_up_needed",
          label: "هل يحتاج متابعة لاحقة؟",
          type: "SELECT",
          isRequired: false,
          order: 5,
          options: [
            ["yes", "نعم"],
            ["no", "لا"],
          ],
        },
        {
          key: "follow_up_date",
          label: "تاريخ المتابعة القادمة",
          type: "DATE",
          isRequired: false,
          order: 6,
          dependsOnFieldKey: "follow_up_needed",
          linkedToValue: "yes",
          options: [],
        },
        {
          key: "internal_notes",
          label: "ملاحظات داخلية",
          type: "TEXTAREA",
          isRequired: false,
          order: 7,
          options: [],
        },
      ],
    },
    {
      title: "الشواهد والمرفقات",
      description: "أرفق أي شواهد داعمة للحالة عند الحاجة.",
      order: 5,
      fields: [
        {
          key: "case_evidence",
          label: "الشواهد",
          type: "FILE_UPLOAD",
          isRequired: false,
          order: 1,
          helpText: "يمكن رفع صورة أو ملف داعم للحالة.",
          options: [],
        },
      ],
    },
  ],
} as const;
