-- CreateTable
CREATE TABLE `ReportTwoActive` (
    `id` VARCHAR(191) NOT NULL,
    `caseEntryId` VARCHAR(191) NOT NULL,
    `schoolAccountId` VARCHAR(191) NOT NULL,
    `serviceSlug` VARCHAR(191) NULL,
    `serviceName` VARCHAR(191) NULL,
    `status` ENUM('SAVED', 'APPROVED', 'ARCHIVED') NOT NULL DEFAULT 'SAVED',
    `reportTitle` VARCHAR(191) NOT NULL,
    `templateId` VARCHAR(191) NULL,
    `templateName` VARCHAR(191) NULL,
    `variantId` VARCHAR(191) NULL,
    `sourcePayload` JSON NOT NULL,
    `editorState` JSON NULL,
    `templateJson` JSON NULL,
    `pagesJson` JSON NULL,
    `renderedHtml` LONGTEXT NOT NULL,
    `renderContext` JSON NULL,
    `previewCase` JSON NULL,
    `pdfUrl` VARCHAR(191) NULL,
    `approvedById` VARCHAR(191) NULL,
    `approvedByName` VARCHAR(191) NULL,
    `approvedAt` DATETIME(3) NULL,
    `savedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `lastSyncedAt` DATETIME(3) NULL,
    `syncMeta` JSON NULL,
    `version` INTEGER NOT NULL DEFAULT 1,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `ReportTwoActive_caseEntryId_key`(`caseEntryId`),
    INDEX `ReportTwoActive_schoolAccountId_idx`(`schoolAccountId`),
    INDEX `ReportTwoActive_serviceSlug_idx`(`serviceSlug`),
    INDEX `ReportTwoActive_status_idx`(`status`),
    INDEX `ReportTwoActive_approvedAt_idx`(`approvedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
