import type { TeacherPerformanceElementCode } from "./teacher-performance-elements";

export type TeacherIntentBlueprint = {
  code: string;
  label: string;
  family: string;
  description: string;
  keywords: string[];
  defaultPerformanceElements: TeacherPerformanceElementCode[];
  recommendedFields: string[];
  avoidUnlessExplicit: string[];
};

export const TEACHER_INTENT_BLUEPRINTS: TeacherIntentBlueprint[] = [
  {
    code: "STUDENT_RECOGNITION",
    label: "تكريم أو تحفيز الطلاب",
    family: "EVENT_ACTIVITY",
    description: "توثيق تكريم الطلاب أو تحفيزهم أو إبراز منجزاتهم.",
    keywords: ["تكريم", "كرمت", "المتفوقين", "المتميزين", "تحفيز", "شكر الطلاب", "جوائز"],
    defaultPerformanceElements: ["learning_environment", "job_duties_performance"],
    recommendedFields: [
      "عنوان التكريم",
      "تاريخ التنفيذ",
      "مكان التنفيذ",
      "الفئة المستهدفة",
      "عدد الطلاب المكرمين",
      "أهداف التكريم",
      "آلية التنفيذ",
      "الشواهد والتوثيق",
      "أثر التكريم على الطلاب",
    ],
    avoidUnlessExplicit: ["تحليل الدرجات", "استراتيجيات التدريس", "خطة علاجية"],
  },
  {
    code: "NATIONAL_EVENT",
    label: "فعالية أو مناسبة وطنية أو مدرسية",
    family: "EVENT_ACTIVITY",
    description: "توثيق مناسبة وطنية أو مدرسية أو برنامج عام.",
    keywords: ["اليوم الوطني", "احتفالية", "مناسبة", "فعالية", "تفعيل", "يوم عالمي", "أسبوع", "إذاعة"],
    defaultPerformanceElements: ["learning_environment", "professional_community_interaction", "job_duties_performance"],
    recommendedFields: [
      "اسم الفعالية أو المناسبة",
      "تاريخ التنفيذ",
      "مكان التنفيذ",
      "الفئة المستهدفة",
      "وصف الفعالية والفقرات المنفذة",
      "الأهداف الوطنية أو التربوية",
      "الشواهد والتوثيق",
      "أثر الفعالية",
    ],
    avoidUnlessExplicit: ["نتائج الاختبار", "مستوى الإتقان", "تحليل الدرجات"],
  },
  {
    code: "LESSON_IMPLEMENTATION",
    label: "تنفيذ درس أو حصة",
    family: "LESSON_PRACTICE",
    description: "توثيق درس أو حصة أو تطبيق خطة تعلم.",
    keywords: ["درس", "حصة", "نفذت درس", "موضوع الدرس", "خطة درس", "نواتج التعلم"],
    defaultPerformanceElements: ["learning_plan_preparation", "teaching_strategies_diversity"],
    recommendedFields: [
      "موضوع الدرس",
      "المادة والصف",
      "تاريخ التنفيذ",
      "الأهداف التعليمية",
      "استراتيجيات التدريس",
      "إجراءات التنفيذ",
      "أدوات التعلم",
      "مشاركة المتعلمين",
      "الشواهد",
    ],
    avoidUnlessExplicit: ["فقرات احتفالية", "شراكة مجتمعية", "تكريم"],
  },
  {
    code: "TEACHING_STRATEGY",
    label: "تطبيق استراتيجية تدريس",
    family: "LESSON_PRACTICE",
    description: "توثيق استخدام استراتيجية تدريس أو تعلم نشط.",
    keywords: ["استراتيجية", "تعلم تعاوني", "عصف ذهني", "تعلم نشط", "حل المشكلات", "فكر زاوج شارك"],
    defaultPerformanceElements: ["teaching_strategies_diversity"],
    recommendedFields: [
      "اسم الاستراتيجية",
      "موضوع الدرس",
      "المادة والصف",
      "مبررات اختيار الاستراتيجية",
      "خطوات تطبيق الاستراتيجية",
      "دور المعلم",
      "دور المتعلمين",
      "الشواهد",
      "أثر الاستراتيجية",
    ],
    avoidUnlessExplicit: ["احتفالية", "تواصل ولي أمر"],
  },
  {
    code: "RESULTS_ANALYSIS",
    label: "تحليل نتائج اختبار أو قياس",
    family: "RESULTS_ANALYSIS",
    description: "تحليل نتائج الطلاب وتشخيص مستوياتهم.",
    keywords: ["تحليل نتائج", "اختبار", "درجات", "إتقان", "مستويات", "نهاية الوحدة", "تشخيص"],
    defaultPerformanceElements: ["learner_results_analysis"],
    recommendedFields: [
      "اسم الاختبار أو الوحدة",
      "المادة والصف",
      "تاريخ الاختبار",
      "عدد الطلاب",
      "مستوى الإتقان",
      "أبرز الفجوات التعليمية",
      "الطلاب المستهدفون بالدعم",
      "الإجراءات المقترحة",
      "مؤشرات التحسن",
    ],
    avoidUnlessExplicit: ["فقرات احتفالية", "تكريم", "مكان الفعالية"],
  },
  {
    code: "REMEDIAL_PLAN",
    label: "خطة علاجية أو دعم للمتعثرين",
    family: "INTERVENTION_PLAN",
    description: "توثيق خطة علاجية لمعالجة جوانب الضعف.",
    keywords: ["خطة علاجية", "متعثر", "ضعف", "دعم", "معالجة", "فجوات", "رفع المستوى"],
    defaultPerformanceElements: ["learner_results_improvement", "learner_results_analysis"],
    recommendedFields: [
      "اسم الخطة العلاجية",
      "الفئة المستهدفة",
      "جوانب الضعف",
      "الأهداف العلاجية",
      "إجراءات التنفيذ",
      "الأدوات المستخدمة",
      "مدة التنفيذ",
      "الشواهد",
      "مؤشرات التحسن",
    ],
    avoidUnlessExplicit: ["احتفالية", "إذاعة", "تكريم"],
  },
  {
    code: "PARENT_COMMUNICATION",
    label: "تواصل مع ولي أمر",
    family: "COMMUNICATION_PARTNERSHIP",
    description: "توثيق تواصل تربوي مع ولي أمر.",
    keywords: ["ولي أمر", "أولياء الأمور", "تواصل", "رسالة", "اتصال", "اجتماع", "غياب ابنه"],
    defaultPerformanceElements: ["parents_interaction"],
    recommendedFields: [
      "موضوع التواصل",
      "تاريخ التواصل",
      "طريقة التواصل",
      "الأطراف المشاركة",
      "سبب التواصل",
      "الإجراءات المتفق عليها",
      "مخرجات التواصل",
      "الشواهد",
      "متابعة لاحقة",
    ],
    avoidUnlessExplicit: ["استراتيجيات التدريس", "تحليل درجات"],
  },
  {
    code: "TECHNOLOGY_USE",
    label: "توظيف منصة أو أداة تقنية",
    family: "TECHNOLOGY_INTEGRATION",
    description: "توثيق استخدام التقنية أو المنصات التعليمية.",
    keywords: ["منصة", "مدرستي", "تقنية", "أداة رقمية", "تطبيق", "وسيلة تعليمية", "بوربوينت"],
    defaultPerformanceElements: ["learning_technology_tools"],
    recommendedFields: [
      "اسم الأداة أو المنصة",
      "الغرض من الاستخدام",
      "المادة والصف",
      "آلية التوظيف",
      "نوع النشاط الرقمي",
      "تفاعل المتعلمين",
      "الشواهد",
      "الأثر على التعلم",
    ],
    avoidUnlessExplicit: ["احتفالية", "تكريم"],
  },
  {
    code: "PROFESSIONAL_COMMUNITY",
    label: "مجتمع مهني أو ورشة أو تبادل خبرات",
    family: "PROFESSIONAL_COMMUNITY",
    description: "توثيق مشاركة المعلم في مجتمع مهني أو ورشة.",
    keywords: ["مجتمع مهني", "ورشة", "تبادل خبرات", "لقاء مهني", "زملاء", "تدريب", "مشرف"],
    defaultPerformanceElements: ["professional_community_interaction"],
    recommendedFields: [
      "عنوان المشاركة المهنية",
      "تاريخ التنفيذ",
      "الجهة أو الأطراف المشاركة",
      "هدف المشاركة",
      "محاور اللقاء",
      "دور المعلم",
      "الشواهد",
      "الأثر المهني",
    ],
    avoidUnlessExplicit: ["تحليل درجات", "خطة علاجية"],
  },
  {
    code: "DUTY_FOLLOWUP",
    label: "واجب وظيفي أو متابعة تكليف",
    family: "DUTY_OPERATIONAL",
    description: "توثيق أداء تكليف أو واجب وظيفي.",
    keywords: ["حصة انتظار", "مناوبة", "تكليف", "واجب وظيفي", "متابعة", "رصد", "التزام"],
    defaultPerformanceElements: ["job_duties_performance"],
    recommendedFields: [
      "نوع المهمة أو التكليف",
      "تاريخ التنفيذ",
      "مكان التنفيذ",
      "الفئة المستفيدة",
      "الإجراءات المنفذة",
      "مستوى الالتزام",
      "الشواهد",
      "الأثر",
    ],
    avoidUnlessExplicit: ["استراتيجيات تدريس", "تحليل نتائج"],
  },
  {
    code: "PORTFOLIO_EVIDENCE",
    label: "ملف إنجاز أو شواهد",
    family: "PORTFOLIO_EVIDENCE",
    description: "توثيق منجز أو شاهد أداء.",
    keywords: ["ملف إنجاز", "شواهد", "توثيق", "منجز", "أدلة", "أعمال"],
    defaultPerformanceElements: ["job_duties_performance", "learning_environment"],
    recommendedFields: [
      "عنوان المنجز",
      "وصف المنجز",
      "مجال الارتباط بالأداء",
      "تاريخ التوثيق",
      "الشواهد المتاحة",
      "أثر المنجز",
      "الدروس المستفادة",
    ],
    avoidUnlessExplicit: ["نتائج اختبار", "فقرات حفل"],
  },
  {
    code: "GENERAL_TEACHER_REPORT",
    label: "تقرير عام للمعلم",
    family: "GENERAL_TEACHER_REPORT",
    description: "يستخدم عندما يكون الوصف عامًا أو غير كاف.",
    keywords: ["تقرير", "توثيق", "تنفيذ", "متابعة", "عمل"],
    defaultPerformanceElements: ["job_duties_performance"],
    recommendedFields: [
      "عنوان التقرير",
      "وصف مختصر",
      "تاريخ التنفيذ",
      "الفئة المستهدفة",
      "الإجراءات المنفذة",
      "الشواهد",
      "الأثر",
    ],
    avoidUnlessExplicit: [],
  },
];

export function getTeacherIntentBlueprint(code: string | undefined | null) {
  return (
    TEACHER_INTENT_BLUEPRINTS.find((item) => item.code === code) ||
    TEACHER_INTENT_BLUEPRINTS[TEACHER_INTENT_BLUEPRINTS.length - 1]
  );
}