server.port=8091
spring.application.name=teachix-timetable-solver

timefold.solver.termination.spent-limit=60s
timefold.solver.termination.best-score-limit=0hard/0soft
timefold.solver.termination.unimproved-spent-limit=10s

logging.level.ai.timefold.solver=INFO
