"use client";
import { useState } from "react";

export function AccountabilitySendControls({ requestId, respondentUserId, respondentPhone }: { requestId: string; respondentUserId: string | null; respondentPhone: string | null }) {
  const [method, setMethod] = useState<"SYSTEM" | "WHATSAPP">("SYSTEM");
  const [result, setResult] = useState<{ url?: string; error?: string }>({});
  const [sending, setSending] = useState(false);
  const disabled = sending || (method === "SYSTEM" ? !respondentUserId : !respondentPhone);
  async function send() { setSending(true); setResult({}); try { const response = await fetch(`/api/dashboard/principal/accountability/${requestId}/send`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ deliveryMethod: method }) }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || "تعذر إرسال الطلب."); setResult({ url: data.whatsappUrl || data.publicUrl }); } catch (error) { setResult({ error: error instanceof Error ? error.message : "تعذر إرسال الطلب." }); } finally { setSending(false); } }
  return <div className="mt-4 space-y-3 border-t border-slate-200 pt-4 dark:border-slate-800"><p className="text-sm font-black text-slate-700 dark:text-slate-200">طريقة الإرسال</p><div className="flex flex-wrap gap-2"><button type="button" onClick={() => setMethod("SYSTEM")} className={`rounded-xl px-4 py-2 text-xs font-black ${method === "SYSTEM" ? "bg-indigo-700 text-white" : "bg-white text-slate-600 ring-1 ring-slate-200"}`}>داخل النظام</button><button type="button" onClick={() => setMethod("WHATSAPP")} className={`rounded-xl px-4 py-2 text-xs font-black ${method === "WHATSAPP" ? "bg-emerald-700 text-white" : "bg-white text-slate-600 ring-1 ring-slate-200"}`}>واتساب</button></div>{disabled && !sending ? <p className="text-xs font-bold text-amber-700">{method === "SYSTEM" ? "يلزم وجود حساب مستجيب داخل المدرسة." : "يلزم وجود رقم جوال للمستجيب."}</p> : null}<button type="button" onClick={() => void send()} disabled={disabled} className="min-h-11 rounded-2xl bg-indigo-700 px-5 text-sm font-black text-white disabled:cursor-not-allowed disabled:opacity-50">{sending ? "جارٍ الإرسال..." : "إرسال الإفادة"}</button>{result.error ? <p className="text-sm font-bold text-rose-600">{result.error}</p> : null}{result.url ? <a href={result.url} target="_blank" rel="noreferrer" className="block text-sm font-black text-emerald-700">{method === "WHATSAPP" ? "فتح واتساب" : "فتح رابط الطلب"}</a> : null}</div>;
}
