import { CurriculumDocumentFooter, CurriculumDocumentHeader } from "@/components/curriculum-distribution/curriculum-document-identity";
import type { ActivityPlanTenPercentRow } from "@/lib/activity-plan/ten-percent-activity-plan-types";
import { formatTenPercentWeeks } from "@/lib/activity-plan/ten-percent-activity-plan-types";
import { ActivityPlanPrintPage, ACTIVITY_PLAN_PRINT_SUBTITLE, activityPlanPrintShellStyles } from "@/components/activity-plan/activity-plan-print-shell";

type Props = { rows: ActivityPlanTenPercentRow[]; gradeSections?: string[]; stage: string; academicYear?: string | null; schoolName: string; educationDepartment?: string | null; logoUrl?: string | null; activityLeaderName?: string | null; activityLeaderSignatureUrl?: string | null; principalName?: string | null; principalSignatureUrl?: string | null };
function displayGrade(value: string) { return String(value || "").replace("::", " ").trim(); }
function groups(rows: ActivityPlanTenPercentRow[]) { const result = new Map<string, ActivityPlanTenPercentRow[]>(); for (const row of rows) for (const combination of (row.grades.length ? row.grades : [""])) { const key = combination || `${row.id}:unassigned`; result.set(key, [...(result.get(key) || []), { ...row, grades: combination ? [combination] : [] }]); } return Array.from(result.entries()).flatMap(([key, pageRows]) => { const chunks: Array<[string, ActivityPlanTenPercentRow[]]> = []; for (let index = 0; index < pageRows.length; index += 8) chunks.push([`${key}:${index}`, pageRows.slice(index, index + 8)]); return chunks; }); }

export function ActivityPlanSemesterPrintDocument({ rows, gradeSections = [], stage, academicYear, schoolName, educationDepartment, logoUrl, activityLeaderName, activityLeaderSignatureUrl, principalName, principalSignatureUrl }: Props) {
  const scopedRows = gradeSections.length ? rows.filter((row) => row.grades.some((value) => gradeSections.includes(value))) : rows;
  const pages = groups(scopedRows); if (!pages.length) pages.push(["empty", []]);
  return <><style>{activityPlanPrintShellStyles}</style><style>{`@page{size:A4 landscape;margin:0}.activity-plan-semester-table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:8.5pt}.activity-plan-semester-table th,.activity-plan-semester-table td{border:.25mm solid #D7E3EA;padding:2.2mm;text-align:center;vertical-align:middle;overflow-wrap:anywhere}.activity-plan-semester-table th{background:#EAF2F8;color:#16324F;font-weight:900}.activity-plan-semester-table td{background:#fff;color:#1F2937;font-weight:700;line-height:1.35}.activity-plan-semester-title{display:flex;align-items:center;justify-content:space-between;gap:5mm;margin:4mm 0;padding:3mm 2mm;border-bottom:2px solid #D7E3EA;background:#EEF4F7;color:#16324F}.activity-plan-semester-title h1{margin:0;font-size:15pt;font-weight:900}.activity-plan-semester-title span{padding:2mm 4mm;border:1px solid #D7E3EA;border-radius:2mm;background:#F1F5F9;font-size:9pt;font-weight:900}.activity-plan-semester-empty{padding:14mm!important;color:#64748B!important}.activity-plan-semester-multiline{white-space:pre-line}`}</style><main className="activity-plan-print-root" dir="rtl">{pages.map(([key, pageRows]) => { const combination = pageRows[0]?.grades[0] || ""; const header = combination ? `${stage} — ${displayGrade(combination)}` : stage; return <ActivityPlanPrintPage key={key} className="activity-plan-ten-percent-print-page activity-plan-print-page--physical" contentClassName="ten-percent-plan-page-content" footer={<CurriculumDocumentFooter primaryRoleLabel="رائد النشاط" primaryName={activityLeaderName} primarySignatureUrl={activityLeaderSignatureUrl} primarySignatureAlt="توقيع رائد النشاط" principalName={principalName} principalSignatureUrl={principalSignatureUrl} />}><CurriculumDocumentHeader title="الخطة الفصلية للنشاط الطلابي" subtitle={ACTIVITY_PLAN_PRINT_SUBTITLE} schoolName={schoolName} educationDepartment={educationDepartment} logoUrl={logoUrl} academicYear={academicYear} /><div className="activity-plan-semester-title"><h1>الخطة الفصلية للنشاط الطلابي</h1><span>{header}</span></div><table className="activity-plan-semester-table"><thead><tr><th>المجال</th><th>البرنامج / النشاط</th><th>أسابيع التنفيذ</th><th>المادة والنوع</th><th>الصف</th><th>المعلم / المعلمون</th></tr></thead><tbody>{pageRows.length ? pageRows.map((row) => <tr key={row.id}><td>{row.domains.map((domain) => domain.title).join("، ") || "—"}</td><td>{row.programs.map((program) => program.name).join("، ") || "—"}</td><td dir="ltr">{formatTenPercentWeeks(row.executionWeeks)}</td><td>{row.subject || "—"}<br/><small>{row.materialType || "أساسية"}</small></td><td>{row.grades.map(displayGrade).join("\n") || "—"}</td><td><div className="activity-plan-semester-multiline">{row.teacherNames.join("\n") || "—"}</div></td></tr>) : <tr><td colSpan={6} className="activity-plan-semester-empty">لا توجد بيانات محفوظة لهذه المرحلة.</td></tr>}</tbody></table></ActivityPlanPrintPage>; })}</main></>;
}
