export const TEACHIX_SUPPORT_EMAIL = "support@teachix.sa";
export const TEACHIX_WHATSAPP_DISPLAY_NUMBER = "0550932995";
export const TEACHIX_WHATSAPP_INTERNATIONAL_NUMBER = "966550932995";
export const TEACHIX_WHATSAPP_URL =
  `https://wa.me/${TEACHIX_WHATSAPP_INTERNATIONAL_NUMBER}`;
