"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import type { MultiPeriodSnapshot } from "@/lib/assessments-center/assessment-types";
import { AssessmentAiEditor } from "./assessment-ai-editor";

export function GenericAnalysisClient({ analysisId }: { analysisId: string }) {
  const [snapshot, setSnapshot] = useState<MultiPeriodSnapshot | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [confirm, setConfirm] = useState(false);
  useEffect(() => { void fetch(`/api/dashboard/assessments-center/${analysisId}`, { cache: "no-store" }).then((response) => response.json()).then((result) => { if (result.success) setSnapshot(result.analysis.summaryJson); else setMessage("تعذر تحميل التحليل."); }); }, [analysisId]);
  async function generateAi() { if (!snapshot || busy) return; if (snapshot.aiMeta?.aiManuallyEdited && !confirm) { setConfirm(true); return; } setConfirm(false); setBusy(true); setMessage("جاري تحليل النتائج وإعداد التقرير..."); try { const response = await fetch("/api/dashboard/assessments-center/ai", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ analysisId }) }); const result = await response.json(); if (!response.ok) throw new Error("تعذر إعداد التحليل الذكي الآن."); setSnapshot(result.snapshot); setMessage("تم تحديث القراءة التربوية والخطط بنجاح."); } catch (error) { setMessage(error instanceof Error ? error.message : "تعذر إعداد التحليل."); } finally { setBusy(false); } }
  if (!snapshot) return <main dir="rtl" className="p-8 font-bold">{message || "جاري تحميل التحليل..."}</main>;
  return <main dir="rtl" className="mx-auto max-w-7xl space-y-6 p-6"><header className="flex flex-wrap items-center justify-between gap-4 rounded-3xl bg-white p-6 shadow-sm"><div><Link href="/dashboard/assessments-center" className="font-bold text-blue-700">العودة إلى التحليلات</Link><h1 className="mt-3 text-3xl font-black">{snapshot.title}</h1><p className="mt-2 font-bold text-slate-500">{snapshot.type === "MAHIROON" ? "اختبار ماهرون" : "تحليل فصلي لمادة"} · {snapshot.subject} · {snapshot.grade} · {snapshot.classroom}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => void generateAi()} disabled={busy} className="rounded-xl bg-violet-700 px-4 py-3 font-black text-white disabled:opacity-60">{busy ? "جاري إعداد التحليل..." : snapshot.ai ? "إعادة توليد التحليل" : "توليد التحليل"}</button><a href={`/dashboard/assessments-center/${analysisId}/print`} target="_blank" rel="noreferrer" className="rounded-xl bg-teal-700 px-4 py-3 font-black text-white">فتح التقرير</a></div></header>{confirm ? <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 font-bold">إعادة التوليد ستستبدل التعديلات المحفوظة يدويًا. <button type="button" onClick={() => void generateAi()} className="mr-3 text-rose-700 underline">متابعة</button><button type="button" onClick={() => setConfirm(false)} className="mr-3 underline">إلغاء</button></div> : null}{message ? <p className="rounded-2xl bg-slate-50 p-4 font-bold">{message}</p> : null}<section className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">المؤشرات حسب الفترة</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{snapshot.periodMetrics.map((period) => <div key={period.periodId} className="rounded-2xl bg-slate-50 p-4"><p className="font-black">{period.label}</p><p className="mt-2 font-bold">المتوسط: {period.average ?? "-"}%</p><p className="font-bold">التحصيل: {period.achievementPercentage ?? "-"}%</p></div>)}</div><p className="mt-5 font-black text-teal-700">التغير من أول فترة إلى آخر فترة: {snapshot.firstToLastAverageChange ?? "-"}%</p></section><section className="overflow-x-auto rounded-3xl border bg-white p-6 shadow-sm"><table className="w-full min-w-[700px] text-right text-sm"><thead className="bg-slate-50"><tr><th className="p-3">الطالب</th>{snapshot.periods.map((period) => <th key={period.id} className="p-3">{period.label}</th>)}<th className="p-3">الاتجاه</th></tr></thead><tbody>{snapshot.students.map((student) => <tr key={student.studentId} className="border-t"><td className="p-3 font-black">{student.studentName}</td>{snapshot.periods.map((period) => <td key={period.id} className="p-3">{student.scores[period.id] ?? "-"}</td>)}<td className="p-3">{student.direction === "IMPROVED" ? "تحسن" : student.direction === "DECLINED" ? "تراجع" : "ثابت"}</td></tr>)}</tbody></table></section><AssessmentAiEditor analysisId={analysisId} ai={snapshot.ai} onSaved={(next) => setSnapshot({ ...snapshot, ai: next })} /></main>;
}
