import crypto from "node:crypto";
import { callDeepSeekChat } from "@/lib/ai/deepseek-client";

export const LEARNING_STYLE_TYPE = "LEARNING_STYLE" as const;
export const LEARNING_STYLES = ["VISUAL", "AUDITORY", "READ_WRITE", "KINESTHETIC"] as const;
export type LearningStyle = (typeof LEARNING_STYLES)[number];
export const LEARNING_STYLE_LABELS: Record<LearningStyle, string> = { VISUAL: "بصري", AUDITORY: "سمعي", READ_WRITE: "قراءة وكتابة", KINESTHETIC: "حركي" };
export type LearningQuestion = { id: string; label: string; options: string[] };
export type LearningStage = "PRIMARY" | "MIDDLE" | "SECONDARY";
const make = (items: Array<[string, string[]]>): LearningQuestion[] => items.map(([label, options], i) => ({ id: `q_${i + 1}`, label, options }));
export const LEARNING_STYLE_BANKS: Record<LearningStage, LearningQuestion[]> = {
  PRIMARY: make([
    ["في الدرس أحب أن أرى...", ["صورة أو رسمًا", "شرحًا بصوت المعلم", "كلمات مكتوبة", "نشاطًا أجربه"]], ["أتذكر المعلومة عندما...", ["أرسمها", "أرددها", "أكتبها", "أطبقها"]], ["لفهم المسألة أفضل...", ["مشاهدة مثال", "سماع الشرح", "قراءة السؤال", "حلها بيدي"]], ["في الواجب أفضل...", ["الألوان والرسوم", "الحوار", "القراءة والكتابة", "الألعاب التعليمية"]], ["إذا لم أفهم أطلب...", ["مثالًا أمامي", "إعادة الشرح", "كتابًا أقرأه", "تجربة أخرى"]], ["أحب ترتيب أفكاري في...", ["خريطة أو صورة", "حديث قصير", "قائمة مكتوبة", "بطاقات أتحرك بها"]], ["عند تعلم كلمة جديدة يساعدني...", ["رؤية صورتها", "سماع نطقها", "كتابتها", "استخدامها في موقف"]], ["في العمل الجماعي أفضل...", ["تصميم لوحة", "التحدث مع الفريق", "كتابة التقرير", "تنفيذ المهمة"]], ["المراجعة الممتعة تكون عبر...", ["صور ومخططات", "أسئلة شفهية", "قراءة الملخص", "تمارين عملية"]], ["أعرف أنني تعلمت عندما أستطيع...", ["رسم الفكرة", "شرحها", "كتابتها", "استخدامها"]],
  ]),
  MIDDLE: make([
    ["عند بدء موضوع جديد أفضّل...", ["مخططًا أو عرضًا", "شرحًا ومناقشة", "قراءة التعريفات", "تطبيقًا"]], ["أنظم ملاحظاتي باستخدام...", ["الأسهم والرسوم", "تسجيل صوتي", "فقرات مكتوبة", "بطاقات نشاط"]], ["لفهم مفهوم صعب أحتاج إلى...", ["مثال مرئي", "شرح متدرج", "مصدر أقرأه", "تدريب عملي"]], ["قبل الاختبار أراجع عبر...", ["خريطة مفاهيم", "مناقشة الدرس", "إعادة كتابة الملخص", "حل الأسئلة"]], ["في الواجب الطويل أبدأ بـ...", ["رسم خطة", "التحدث عن المطلوب", "قراءة التعليمات", "تقسيم المهام"]], ["عند تصحيح خطئي أستفيد من...", ["رؤية موضعه", "سماع تفسيره", "قراءة التصحيح", "إعادة المحاولة"]], ["في المشروع أميل إلى...", ["تصميم العرض", "تقديم الفكرة", "تحرير التقرير", "بناء النموذج"]], ["الدرس المسجل يفيدني إذا...", ["ظهرت معه رسوم", "استمعت إليه", "قرأت نصه", "طبقت خطواته"]], ["أتذكر خطوات العمل إذا...", ["رأيتها مرتبة", "سمعتها", "كتبتها", "نفذتها"]], ["أتحقق من فهمي عندما...", ["أرسم الفكرة", "أشرحها", "أكتب ملخصًا", "أحل موقفًا"]],
  ]),
  SECONDARY: make([
    ["عند دراسة مفهوم متقدم أبدأ بـ...", ["نموذج أو مخطط", "محاضرة أو نقاش", "مرجع مكتوب", "تجربة تطبيقية"]], ["ألخص فصلًا دراسيًا عبر...", ["خريطة مفاهيم", "شرح مسموع", "ملخص تحريري", "أمثلة تطبيقية"]], ["في مراجعة الاختبار أركز على...", ["الجداول والرسوم", "مناقشة الأفكار", "إعادة القراءة والكتابة", "حل مسائل متنوعة"]], ["لفهم العلاقة بين فكرتين أستخدم...", ["رسم العلاقة", "شرحًا شفهيًا", "مقارنة مكتوبة", "تجربة توضحها"]], ["في مشروع بحثي أفضل...", ["تصميم العرض", "تقديم النتائج", "تحرير التقرير", "جمع الأدلة وبناء النموذج"]], ["مع مصدر معقد أحتاج إلى...", ["تمثيل بصري", "شرح مناقش", "قراءته بتركيز", "ربطه بممارسة"]], ["أتأكد من فهمي عندما...", ["أنظم الفكرة بصريًا", "أدافع عنها في نقاش", "أكتب تفسيرًا", "أستخدمها في حالة جديدة"]], ["المراجعة الجماعية تفيدني إذا كانت...", ["بمخططات", "حوارًا", "ملاحظات مكتوبة", "تمارين"]], ["في التعلم المستقل أفضّل...", ["دليلًا مصورًا", "شرحًا صوتيًا", "تعليمات مكتوبة", "تجربة متدرجة"]], ["أفضل إظهار ما تعلمته عبر...", ["عرض بصري", "عرض شفهي", "تقرير", "منتج عملي"]],
  ]),
};
export function learningStageForGrade(grade: string): LearningStage { if (/ابتد|primary|[1-6]/i.test(grade)) return "PRIMARY"; if (/متوسط|middle|[7-9]/i.test(grade)) return "MIDDLE"; return "SECONDARY"; }
export function createLearningStyleToken() { return crypto.randomBytes(24).toString("base64url"); }
function parse(value: string) { try { return JSON.parse(value.replace(/^```json\s*/i, "").replace(/\s*```$/i, "")); } catch { return null; } }
export async function classifyLearningStyleBatch(input: { grade: string; classroom: string; stage: LearningStage; students: Array<{ studentKey: string; answers: Array<{ questionId: string; question: string; answerId: string; answerText: string }> }> }) {
  const content = await callDeepSeekChat({ temperature: 0, maxTokens: 1800, responseFormat: "json_object", messages: [{ role: "system", content: "Return JSON only with students, classroomInterpretation, recommendations. Return exactly one item for every input student, preserve every studentKey exactly once, no extra or missing students. learningStyle must be exactly VISUAL, AUDITORY, READ_WRITE, or KINESTHETIC. Classify only from the ten supplied answers; do not invent scores, facts, or traits; do not calculate percentages." }, { role: "user", content: JSON.stringify(input) }] });
  const result = parse(content) as { students?: Array<{ studentKey?: string; learningStyle?: string }>; classroomInterpretation?: string; recommendations?: string[] } | null;
  const expected = input.students.map(s => s.studentKey); const returned = result?.students || [];
  if (returned.length !== expected.length || new Set(returned.map(s => s.studentKey)).size !== expected.length || returned.some(s => !s.studentKey || !expected.includes(s.studentKey) || !LEARNING_STYLES.includes(s.learningStyle as LearningStyle))) throw new Error("INVALID_LEARNING_STYLE_BATCH");
  return { students: returned.map(s => ({ studentKey: s.studentKey as string, learningStyle: s.learningStyle as LearningStyle })), classroomInterpretation: String(result?.classroomInterpretation || "").slice(0, 5000), recommendations: Array.isArray(result?.recommendations) ? result!.recommendations!.filter(x => typeof x === "string").slice(0, 20) : [] };
}
export function aggregateLearningStyles(values: Array<{ learningStyle?: unknown }>) { const analyzed = values.filter(v => LEARNING_STYLES.includes(v.learningStyle as LearningStyle)); const counts = Object.fromEntries(LEARNING_STYLES.map(s => [s, analyzed.filter(v => v.learningStyle === s).length])) as Record<LearningStyle, number>; const total = analyzed.length; const percentages = Object.fromEntries(LEARNING_STYLES.map(s => [s, total ? Number((counts[s] / total * 100).toFixed(2)) : 0])) as Record<LearningStyle, number>; const top = Math.max(...LEARNING_STYLES.map(s => counts[s]), 0); const leaders = LEARNING_STYLES.filter(s => counts[s] === top && top > 0); return { analyzedStudentCount: total, counts, percentages, dominant: leaders.length === 1 ? leaders[0] : null, tied: leaders.length > 1 }; }
